version: '3.9'

services:
  postgres:
    image: postgres:16-alpine    # 🟢 smaller, faster image (~60 MB)
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234          # simple password ok for local use
      POSTGRES_DB: testdb
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork
    deploy:
      resources:                       # optional resource limits
        limits:
          memory: 512M                 # cap at ~512 MB
        reservations:
          memory: 128M

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
