version: "3.9"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "YourStrong!Passw0rd"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    networks:
      - my_network
    volumes:
      - sql_data:/var/opt/mssql
    restart: unless-stopped

networks:
  my_network:
    driver: bridge

volumes:
  sql_data:
